igorbasko01/stuff-doer

src/main/DatabaseActor.scala
Get the Unfinished Actions from the database.
=> Feature init unfinished

src/main/DatabaseActor.scala, src/main/MasterActor.scala
Currently it is empty. Need to add a function that will fill it up.
Need to submit first the following PRs:
[] #1
=> Feature init unfinished use, depends on #1

pom.xml, resources/html/index.html, resources/html/script.js, src/main/DatabaseActor.scala, src/main/FileActor.scala, src/main/HttpClient.scala, src/main/MasterActor.scala, src/main/WebServerActor.scala
Merge all changes, to start working on Basched
=> Feature copy actor

resources/html/index.html, resources/html/script.js, src/main/MasterActor.scala
and remove the scheduling of unfinished actions.
=> Add a simple timer

src/main/Basched.scala, src/main/DatabaseActor.scala, src/main/MasterActor.scala, src/main/WebServerActor.scala
Using a new way for request/reply without the ask pattern.
=> Feature database create tables

resources/html/index.html, resources/html/script.js
=> Display task priority

src/main/BaschedRequest.scala, src/main/WebServerActor.scala
=> Create task selection logic

resources/html/index.html, resources/html/script.js, src/main/Basched.scala, src/main/BaschedRequest.scala
=> Display the selected task separatly

README.md
=> Add the README file

actions-2017-06-19.txt, actions-2017-06-21.txt, actions.txt
=> Delete action files

resources/html/index.html, resources/html/script.js, src/main/Basched.scala, src/main/BaschedRequest.scala, src/main/WebServerActor.scala
=> Insert rows into RECORDS table

resources/html/script.js, src/main/Basched.scala, src/main/BaschedRequest.scala, src/main/WebServerActor.scala
=> Feature calc remaining time

resources/html/index.html, resources/html/script.js, src/main/Basched.scala, src/main/BaschedRequest.scala, src/main/WebServerActor.scala
=> Feature handle pomodoro end

resources/html/script.js, src/main/BaschedRequest.scala, src/main/WebServerActor.scala
=> Feature update task selection algorithm

resources/html/AddTask.js, resources/html/index.html, resources/html/script.js, src/main/BaschedRequest.scala, src/main/WebServerActor.scala
=> Feature dont select window finished

resources/html/index.html, resources/html/script.js, src/main/Basched.scala, src/main/BaschedRequest.scala, src/main/WebServerActor.scala
=> Feature disable start button

resources/html/script.js, src/main/Basched.scala, src/main/WebServerActor.scala
=> Feature create on hold button

resources/html/script.js, src/main/BaschedRequest.scala
=> Feature frontend sync requests

src/main/resources/html/script.js, src/main/scala/scheduler/Basched.scala, src/main/scala/scheduler/BaschedRequest.scala, src/main/scala/webserver/WebServerActor.scala
=> Feature server tracks time

src/main/resources/html/script.js, src/main/scala/scheduler/BaschedRequest.scala, src/main/scala/webserver/WebServerActor.scala
=> Feature update priority

src/main/resources/html/AddTask.js, src/main/resources/html/script.js, src/main/scala/scheduler/BaschedRequest.scala
=> Bug handle special characters

Dockerfile, src/main/resources/application.conf, src/main/resources/html/AddTask.html, src/main/resources/html/AddTask.js, src/main/resources/html/globals.js, src/main/resources/html/index.html, src/main/resources/html/script.js
=> Add a Dockerfile and update relevant code

src/main/resources/html/AddTask.js, src/main/scala/scheduler/BaschedRequest.scala
=> Bug issue#67

src/main/resources/html/script.js
=> Move the playing of the alarm to the top of the notify function

src/main/resources/html/AddTask.html, src/main/resources/html/ReportDailyStatus.html, src/main/resources/html/ReportDailyStatus.js, src/main/resources/html/globals.js, src/main/resources/html/index.html, src/main/resources/html/script.js, src/main/scala/scheduler/BaschedRequest.scala, src/main/scala/webserver/RouteContainer.scala, src/main/scala/webserver/WebServerActor.scala, src/main/scala/webserver/WebServerJsonReply.scala
=> Feature daily status report

src/main/resources/html/ReportDailyStatus.js
=> Convert the duration per task in the daily report to be in minutes.

.gitignore, build.sbt, project/Dependencies.scala, project/build.properties
And ignore ENSIME files.
Fix #105
=> Feature add sbt

Dockerfile, README.md
Add some description on how to build and run the project.
Fix #93
=> Feature docker doc

src/main/scala/scheduler/BaschedRequest.scala
Fix #106
limit in the insertion the record duration to pomodoro max duration by taking the min between them.
=> Issue # 106

.gitignore, .travis.yml, Dockerfile, src/main/resources/logback.xml
Now the docker image will build easily locally and also appropriately to production.
Fix #113
=> Feature fix dockerfile

src/main/resources/html/Enums.js, src/main/resources/html/index.html, src/main/resources/html/script.js, src/main/scala/scheduler/BaschedRequest.scala, src/main/scala/webserver/RouteContainer.scala
=> Feature global timer

src/main/resources/html/BreakTimer.js, src/main/resources/html/index.html, src/main/resources/html/script.js
=> Feature break timer
